version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sentinelx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/sentinelx.db:/app/sentinelx.db
      - ./backend/generated_reports:/app/generated_reports
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./frontend
    container_name: sentinelx_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
