import React from "react";
import "../styles/pdfReport.css";

export default function PDFReport({ result, website }) {
  if (!result) return null;

  const reportDate = new Date();
  const score = Number(result.security_score || 0);
  const risk = result.risk_level || "Unknown";
  const ssl = result.ssl || {};
  const headers = result.headers || {};
  const dns = result.dns || {};
  const whois = result.whois || {};
  const technology = result.technology || {};
  const ports = result.open_ports || [];
  const recommendations = result.recommendations || [];

  const circumference = 565;
  const progress = circumference - (score / 100) * circumference;

  let grade = "F";
  if (score >= 90) grade = "A+";
  else if (score >= 80) grade = "A";
  else if (score >= 70) grade = "B";
  else if (score >= 60) grade = "C";
  else if (score >= 50) grade = "D";

  const severity = {
    critical: result.critical !== undefined ? result.critical : (score < 30 ? 3 : 0),
    high: result.high !== undefined ? result.high : (score < 60 ? 4 : 2),
    medium: result.medium !== undefined ? result.medium : (score < 80 ? 6 : 2),
    low: result.low !== undefined ? result.low : (score > 70 ? 8 : 4)
  };

  const findings = [
    { title: "SSL Security", value: ssl.valid ? "Secure" : "Insecure" },
    { title: "Security Headers", value: Object.keys(headers).length },
    { title: "Open Ports", value: ports.length },
    { title: "DNS Intelligence", value: Object.keys(dns).length },
    { title: "WHOIS Records", value: Object.keys(whois).length },
    { title: "Tech Fingerprints", value: Object.keys(technology).length }
  ];

  const renderFooter = () => (
    <footer className="pdf-page-footer">
      <span className="footer-platform">Generated by SentinelX Security Platform</span>
      <span className="footer-timestamp">Date: {reportDate.toLocaleDateString()} | Time: {reportDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
    </footer>
  );

  return (
    <div id="pdf-report">
      {/* PAGE 1: COVER PAGE */}
      <div className="pdf-page cover-page-container">
        <div className="cover-logo-area">
          <div className="cover-icon">🛡</div>
          <h1>Sentinel<span>X</span></h1>
          <p className="cover-tagline">Enterprise Cybersecurity Assessment & Risk Report</p>
        </div>

        <div className="cover-card-container">
          <div className="cover-field">
            <span>Target Domain</span>
            <h3>{website}</h3>
          </div>
          <div className="cover-field">
            <span>Security Rating</span>
            <h3 className={`cover-grade ${grade.startsWith("A") ? "text-green" : "text-orange"}`}>{grade} ({score}/100)</h3>
          </div>
          <div className="cover-field">
            <span>Risk Index</span>
            <h3 className={`cover-risk ${risk === "Low" ? "text-green" : "text-red"}`}>{risk} Risk</h3>
          </div>
          <div className="cover-field">
            <span>Report Timestamp</span>
            <h3>{reportDate.toLocaleDateString()} at {reportDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</h3>
          </div>
        </div>

        <div className="cover-branding-footer">
          <p>This automated assessment report analyzes HTTP headers, SSL validity, DNS exposure, technology fingerprinting, and open network ports. The contents are confidential and intended for systems administration review.</p>
        </div>
        {renderFooter()}
      </div>

      {/* PAGE 2: EXECUTIVE SUMMARY & METRIC STATS */}
      <div className="pdf-page">
        <section className="pdf-section">
          <h2>Executive Summary</h2>
          <p>
            An automated external assessment has been conducted for the target website <strong>{website}</strong>. 
            The system evaluated SSL configurations, web technology frameworks, DNS records, public WHOIS registration data, 
            HTTP security headers, and network port exposure.
          </p>
          <p style={{ marginTop: "10px" }}>
            The target received an overall security score of <strong>{score}/100</strong>, which classifies it as a <strong>{risk} Risk</strong> rating. 
            Review the detailed severity distribution below and prioritize remediating any high or critical findings.
          </p>
        </section>

        <section className="dashboard-grid">
          <div className="score-panel">
            <h3>Overall Security Score</h3>
            <div className="gauge">
              <svg width="180" height="180" viewBox="0 0 220 220">
                <circle cx="110" cy="110" r="90" stroke="#f1f5f9" strokeWidth="18" fill="none" />
                <circle
                  cx="110"
                  cy="110"
                  r="90"
                  stroke={score >= 80 ? "#10b981" : score >= 60 ? "#f59e0b" : "#ef4444"}
                  strokeWidth="18"
                  fill="none"
                  strokeDasharray={circumference}
                  strokeDashoffset={progress}
                  strokeLinecap="round"
                  transform="rotate(-90 110 110)"
                />
                <text x="110" y="105" textAnchor="middle" className="score-number">{score}</text>
                <text x="110" y="130" textAnchor="middle" className="score-label">/ 100</text>
              </svg>
            </div>
            <div className="grade-chip">Grade Score: {grade}</div>
          </div>

          <div className="risk-panel">
            <h3>Exposure & Risk Analysis</h3>
            <div className="risk-bar">
              <div className={`risk-fill ${risk.toLowerCase()}`} />
            </div>
            <div className="risk-title">{risk} Exposure Index</div>
            <div className="risk-scale">
              <span>Low</span>
              <span>Medium</span>
              <span>High</span>
              <span>Critical</span>
            </div>
          </div>
        </section>

        <section className="pdf-section">
          <h2>Attack Surface Summary</h2>
          <div className="finding-grid">
            {findings.map((item, index) => (
              <div key={index} className="finding-card">
                <h4>{item.title}</h4>
                <h1>{item.value}</h1>
              </div>
            ))}
          </div>
        </section>

        <section className="pdf-section">
          <h2>Vulnerability Severity Mix</h2>
          <div className="severity-grid">
            <div className="severity-card critical">
              <h3>Critical</h3>
              <h1>{severity.critical}</h1>
            </div>
            <div className="severity-card high">
              <h3>High</h3>
              <h1>{severity.high}</h1>
            </div>
            <div className="severity-card medium">
              <h3>Medium</h3>
              <h1>{severity.medium}</h1>
            </div>
            <div className="severity-card low">
              <h3>Low</h3>
              <h1>{severity.low}</h1>
            </div>
          </div>
        </section>
        {renderFooter()}
      </div>

      {/* PAGE 3: CRYPTOGRAPHY & SECURITY HEADERS */}
      <div className="pdf-page">
        <section className="pdf-section">
          <h2>SSL / TLS Cryptographic Analysis</h2>
          <div className="info-grid">
            <div className="info-card">
              <span>Certificate Status</span>
              <h3>{ssl.valid ? "Valid & Secure SSL" : "Invalid / Expired SSL Certificate"}</h3>
            </div>
            <div className="info-card">
              <span>TLS Protocol</span>
              <h3>{ssl.protocol || "TLS v1.3 / v1.2 Enabled"}</h3>
            </div>
            <div className="info-card">
              <span>Certificate Issuer</span>
              <h3>
                {typeof ssl.issuer === "object"
                  ? ssl.issuer.organizationName || ssl.issuer.O || ssl.issuer.commonName || ssl.issuer.CN || Object.values(ssl.issuer)[0] || "Unknown"
                  : ssl.issuer || "Unknown Issuer"}
              </h3>
            </div>
            <div className="info-card">
              <span>Certificate Expiration</span>
              <h3>{ssl.expires || ssl.expiry || "Unknown Expiry"}</h3>
            </div>
          </div>
        </section>

        <section className="pdf-section">
          <h2>HTTP Security Header Compliance</h2>
          <table className="pdf-table">
            <thead>
              <tr>
                <th>Security Header Name</th>
                <th>Evaluation Status</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(headers).length > 0 ? (
                Object.entries(headers).map(([key, value], index) => (
                  <tr key={index}>
                    <td><strong>{key}</strong></td>
                    <td className={value ? "text-green" : "text-orange"}>{value || "Missing / Not Configured"}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="2">HTTP security header information is unavailable for this target.</td>
                </tr>
              )}
            </tbody>
          </table>
        </section>
        {renderFooter()}
      </div>

      {/* PAGE 4: DNS, WHOIS & TECHNOLOGY FINGERPRINT */}
      <div className="pdf-page">
        <section className="pdf-section">
          <h2>DNS Record Intelligence</h2>
          <table className="pdf-table">
            <thead>
              <tr>
                <th style={{ width: "80px" }}>Type</th>
                <th>Record Configuration Values</th>
              </tr>
            </thead>
            <tbody>
              {Object.keys(dns).length ? (
                Object.entries(dns).map(([key, value], index) => (
                  <tr key={index}>
                    <td><strong>{key}</strong></td>
                    <td style={{ fontSize: "13px" }}>
                      {Array.isArray(value) ? value.join(", ") : value || "Not Configured"}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="2">DNS record database information is unavailable.</td>
                </tr>
              )}
            </tbody>
          </table>
        </section>

        <section className="pdf-section">
          <h2>Domain Registration WHOIS Intelligence</h2>
          <table className="pdf-table">
            <thead>
              <tr>
                <th>Registration Registry Field</th>
                <th>Value Record</th>
              </tr>
            </thead>
            <tbody>
              {Object.keys(whois).length ? (
                Object.entries(whois).slice(0, 10).map(([key, value], index) => (
                  <tr key={index}>
                    <td><strong>{key.replaceAll("_", " ")}</strong></td>
                    <td>{value || "Not Disclosed / Private"}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="2">WHOIS privacy filters are blocking registration record retrieval.</td>
                </tr>
              )}
            </tbody>
          </table>
        </section>

        <section className="pdf-section">
          <h2>Platform Technology Fingerprints</h2>
          <div className="tech-grid">
            {Object.keys(technology).length ? (
              Object.entries(technology).map(([key, value], index) => (
                <div key={index} className="tech-card">
                  <h4>{key.replaceAll("-", " ").replaceAll("_", " ")}</h4>
                  <p>{Array.isArray(value) ? value.join(", ") : value || "Fingerprinted"}</p>
                </div>
              ))
            ) : (
              <div className="tech-card" style={{ gridColumn: "span 3" }}>
                <p>No framework, server headers or CMS signatures were identified during fingerprinting.</p>
              </div>
            )}
          </div>
        </section>
        {renderFooter()}
      </div>

      {/* PAGE 5: NETWORK exposure, RECOMMENDATIONS & CONCLUSION */}
      <div className="pdf-page">
        <section className="pdf-section">
          <h2>Network Port Exposure</h2>
          <table className="pdf-table">
            <thead>
              <tr>
                <th>Port Number</th>
                <th>Service Name</th>
                <th>Risk Exposure Level</th>
              </tr>
            </thead>
            <tbody>
              {ports.length ? (
                ports.map((portInfo, index) => (
                  <tr key={index}>
                    <td><strong>{portInfo.port || portInfo}</strong></td>
                    <td>{portInfo.service || "Identified service"}</td>
                    <td className="text-orange">Exposed Port</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="3" className="text-green" style={{ fontWeight: "600" }}>✓ No dangerous public-facing network ports exposed.</td>
                </tr>
              )}
            </tbody>
          </table>
        </section>

        <section className="pdf-section">
          <h2>Recommended Remediation Actions</h2>
          <div className="recommendation-grid">
            {recommendations.length ? (
              recommendations.map((rec, index) => (
                <div key={index} className="recommendation-box">
                  <div className="recommendation-number">{index + 1}</div>
                  <p style={{ margin: "0", fontSize: "14px" }}>{rec}</p>
                </div>
              ))
            ) : (
              <div className="recommendation-box" style={{ borderColor: "#10b981" }}>
                <div className="recommendation-number" style={{ background: "#10b981" }}>✓</div>
                <p style={{ margin: "0", fontSize: "14px" }}>No immediate vulnerabilities were compiled by the risk assessment engine.</p>
              </div>
            )}
          </div>
        </section>

        <section className="conclusion-section">
          <h2>Security Conclusion</h2>
          <div className="conclusion-box">
            <p>
              This automated SentinelX assessment indicates that the target <strong>{website}</strong> has a 
              vulnerability footprint matching a <strong>{risk} Risk</strong> rating. Implementing the compiled HTTP header configurations, 
              maintaining strong cipher suites in SSL, and restricting unnecessary port exposure will greatly improve security posture.
            </p>
            <p style={{ marginTop: "12px", fontSize: "13px", color: "#64748b", fontStyle: "italic" }}>
              Disclaimer: This report was dynamically generated from external signatures. A full cybersecurity audit should always be conducted.
            </p>
          </div>
        </section>
        {renderFooter()}
      </div>
    </div>
  );
}