from io import BytesIO
from reportlab.lib.colors import black, HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def generate_pdf(report_data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()

    elements = []

    # Title
    elements.append(
        Paragraph(
            "<b>SentinelX Digital Security Assessment Report</b>",
            styles["Title"],
        )
    )
    elements.append(Spacer(1, 10))

    # Metadata
    gen_time = report_data.get("generated_at") or "Latest Scan"
    elements.append(
        Paragraph(
            f"<b>Platform Metadata:</b> Generated at {gen_time} | SentinelX v2.0",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 15))

    # Executive Summary Section
    elements.append(
        Paragraph("<b>1. Executive Summary</b>", styles["Heading2"])
    )
    elements.append(Spacer(1, 6))

    total_assessments = report_data.get("total_assessments", 0)
    total_findings = report_data.get("total_findings", 0)
    critical = report_data.get("critical", 0)
    high = report_data.get("high", 0)
    medium = report_data.get("medium", 0)
    low = report_data.get("low", 0)
    owasp_count = report_data.get("owasp_findings", 0)

    exec_summary_text = (
        f"This report presents an aggregated security assessment generated by SentinelX. "
        f"A total of <b>{total_assessments}</b> target assessment(s) have been completed, identifying "
        f"<b>{total_findings}</b> security finding(s) (Critical: {critical}, High: {high}, Medium: {medium}, Low: {low}). "
        f"OWASP security findings count: <b>{owasp_count}</b>."
    )
    elements.append(Paragraph(exec_summary_text, styles["Normal"]))
    elements.append(Spacer(1, 15))

    # Metric Table (Preserving original metric table & extending)
    elements.append(
        Paragraph("<b>2. Risk & Severity Breakdown</b>", styles["Heading2"])
    )
    elements.append(Spacer(1, 6))

    table_data = [
        ["Metric Indicator", "Value"],
        ["Total Assessments", str(total_assessments)],
        ["Total Findings", str(total_findings)],
        ["Critical Severity", str(critical)],
        ["High Severity", str(high)],
        ["Medium Severity", str(medium)],
        ["Low Severity", str(low)],
        ["OWASP Findings Count", str(owasp_count)],
    ]

    table = Table(table_data, colWidths=[220, 180])
    table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, black),
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#dbeafe")),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
                ("TOPPADDING", (0, 1), (-1, -1), 6),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 15))

    # Tool Status Section
    elements.append(
        Paragraph("<b>3. Backend Tool Status Matrix</b>", styles["Heading2"])
    )
    elements.append(Spacer(1, 6))

    tools_status = report_data.get("tools_status", {})
    nmap_status = "✓ Installed & Operational" if tools_status.get("nmap_installed") else "✗ Not Installed"
    zap_inst = "✓ Binary Available" if tools_status.get("zap_installed") else "✗ Binary Not Detected"
    zap_run = "✓ API Online & Reachable" if tools_status.get("zap_running") else "✗ Offline / Not Reachable"

    tools_table_data = [
        ["Security Module", "Backend Environment Status"],
        ["Nmap Port Scanner", nmap_status],
        ["OWASP ZAP Binary", zap_inst],
        ["OWASP ZAP REST API", zap_run],
    ]
    tools_table = Table(tools_table_data, colWidths=[220, 180])
    tools_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, black),
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#e2e8f0")),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
                ("TOPPADDING", (0, 1), (-1, -1), 6),
            ]
        )
    )
    elements.append(tools_table)
    elements.append(Spacer(1, 15))

    # Recommendations Section
    elements.append(
        Paragraph("<b>4. Core Recommendations & Remediation</b>", styles["Heading2"])
    )
    elements.append(Spacer(1, 6))
    recs = [
        "1. Ensure HTTP Strict Transport Security (HSTS) and Content Security Policy (CSP) headers are active on all public web endpoints.",
        "2. Review open ports and ensure administrative interfaces (FTP, Telnet, SSH, RDP) are firewalled or restricted.",
        "3. Maintain up-to-date SSL/TLS certificates and enforce TLS 1.2+ across web servers.",
        "4. Import or connect local OWASP ZAP assessment results to continuously monitor application vulnerabilities."
    ]
    for r in recs:
        elements.append(Paragraph(r, styles["Normal"]))
        elements.append(Spacer(1, 4))

    elements.append(Spacer(1, 20))
    elements.append(
        Paragraph(
            "<b>Generated by SentinelX 2.0</b> — Digital Security Assessment & Reporting Platform",
            styles["Heading3"],
        )
    )

    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf