from io import BytesIO
from reportlab.lib.colors import black
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def generate_pdf(report_data):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "<b>SentinelX Security Assessment Report</b>",
            styles["Title"],
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "Intelligent Security Assessment & Reporting Platform",
            styles["Heading2"],
        )
    )

    elements.append(Spacer(1, 20))

    table_data = [
        ["Metric", "Value"],
        ["Total Assessments", report_data["total_assessments"]],
        ["Total Findings", report_data["total_findings"]],
        ["Critical", report_data["critical"]],
        ["High", report_data["high"]],
        ["Medium", report_data["medium"]],
        ["Low", report_data["low"]],
    ]

    table = Table(table_data, colWidths=[220, 180])

    table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, black),
                ("BACKGROUND", (0, 0), (-1, 0), "#dbeafe"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("TOPPADDING", (0, 0), (-1, 0), 10),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
                ("TOPPADDING", (0, 1), (-1, -1), 8),
            ]
        )
    )

    elements.append(table)

    elements.append(Spacer(1, 30))

    elements.append(
        Paragraph(
            "Generated by SentinelX",
            styles["Heading3"],
        )
    )

    elements.append(
        Paragraph(
            "© Security Assessment Platform",
            styles["Normal"],
        )
    )

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf